### ISSUE TITLE
New tab button jumps to right when undo button is added to tab bar

### ISSUE THREAD

**Issue by rugk** [M-Reimer/undoclosetab#21]
It's an upstream bug, but just so you know: https://bugzilla.mozilla.org/show_bug.cgi?id=1418086

**Comment by rugk** [comment]
Okay, maybe it actually is not an upstream bug. Upstream said I should report it to you… So here you are:

User Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
Build ID: 20171030111120

Steps to reproduce:

1. Install https://addons.mozilla.org/en-US/firefox/addon/undoclosetabbutton/
2. Customize the UI to move the icon into the tab bar, right of the + (new tab) button.

**Actual results:**

The new tab button is also shown at the right. (see screenshot)
After a Firefox restart, the button is right back at the correct position (next right to the last opened tab).

**Expected results:**

Leave the + button where it is – next to the current/last opened tab.

**Comment by M-Reimer** [comment]
Actually it is a bit funny that Mozilla points you back to me, as all I do is creating a so called "browser Action" which is basic WebExtensions API functionality. If this doesn't work, then the bug is inside Firefox.

I tried to reproduce your issue and I'm not able to get your behaviour. The button keeps where it should be. Maybe this has something to do with a somehow "broken" Firefox profile or it is distribution dependend (I use Arch Linux). Can you please try a fresh Firefox profile and report back if it works there?

**Comment by rugk** [comment]
I just tried it with a different (small) profile with Firefox 58.0b4.

Here is a screencast: 
[buttonmove.zip](https://github.com/M-Reimer/undoclosetab/files/1483904/buttonmove.zip)

**Comment by M-Reimer** [comment]
No I see what you mean. This is not bug in my Addon. It happens with other Addons and most probably even with Firefox built-in buttons. I commented your bug and added some more info. I'm closing this one, as there is nothing I can do to fix this.
