### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by Maggy11** [M-Reimer/undoclosetab#24]
Hi,
I installed undoclosetab in Firefox v57 64bits under Windows 7, but nothing happens when I left click the icon next to the address bar.

**Comment by M-Reimer** [comment]
I've tried on the Windows 10 system of a friend and there everything worked perfectly.
What happens if you right-click on the icon? Did you close some tabs *after* installing the addon?

**Comment by Maggy11** [comment]
This is Windows 7, perhaps that's the difference? When I right click, it shows a menu with 5 standard firefox options (in Dutch, because my firefox is dutch, and I'm dutch). Yes, I want to use it just to reopen tabs that I accidentally close, and all off these tabs are created and closed after installing the addon. That's what it's meant to do, right? But it doesn't. BTW other installed active addons: Reader, Pinterest, uBlock, Tab Center Redux, MySessions, https everywhere,  TabZen. They all do work.

**Comment by M-Reimer** [comment]
Exactly that is what it's meant to do.
Would be pretty interesting to know if you get any error messages.

Please uninstall "undo close tab" and then go to the Firefox menu, choose "Web Developer" there and "Browser Console" from the submenu. Alternative: (Ctrl + Shift + J)

In the Browser Console clear all messages using the upper left button.
Now disable "CSS" and "Server" messages.

Now install "undo close tab". After doing so, click the button on the toolbar. Keep watching the Browser Console and copy messages, that may be interesting, to this bug report.

I hope I can actually read them if you are using a dutch version.

**Comment by Rockemail** [comment]
I have same problem. I encounter this problem since Firefox 57, then 58 and Nightly 59.
It got work normally few days before, but still not work now.

Browser Console messages: (I clicked the button 2 times)
1512715455149	addons.xpi	WARN	Failed to remove temporary file C:\Users\Administrator\AppData\Local\Temp\tmp-jiy.xpi for addon https://addons.mozilla.org/firefox/downloads/file/748802/geschlossenen_tab_wiederherstellen-4.1.0-an+fx.xpi?src=dp-btn-primary: [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.remove]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: resource://gre/modules/addons/XPIInstall.jsm :: removeTemporaryFile :: line 1556"  data: no] Stack trace: removeTemporaryFile()@resource://gre/modules/addons/XPIInstall.jsm:1556 < startInstall/<()@resource://gre/modules/addons/XPIInstall.jsm:1911
entry is undefined  ext-browser.js:730
<unavailable>  background.js:33
TypeError: tabs is undefined  background.js:104:1
entry is undefined  ext-browser.js:730
<unavailable>  background.js:33
entry is undefined  ext-browser.js:730
<unavailable>  background.js:33
entry is undefined  ext-browser.js:730
<unavailable>  background.js:33
entry is undefined  ext-browser.js:730
<unavailable>  background.js:33
Use inbox feed  mailAccount.js:238
entry is undefined  ext-browser.js:730
<unavailable>  background.js:33
entry is undefined  ext-browser.js:730
<unavailable>  background.js:33

Sorry about my bad English.

**Comment by M-Reimer** [comment]
I'm unable to reproduce your errors... I even tried with the latest Nightly version.
Can you reproduce the problem with the (soon available) 4.1.1 version? If so, maybe you could provide a step-by-step list of what to do, beginning with the start of a new Firefox instance?

**Comment by Rockemail** [comment]
Even 4.1.1 version get this error, but I don' t know how to reproduce this problem.
Then after I Refresh Firefox (Nightly) and install all addon I use, it works normally...
Maybe something wrong with Firefox itself?
I'll try to get how to reproduce about this problem.
Thank you.

**Comment by Filbuntu** [comment]
Hi! Thank you for the helpful add-on! 
I have a similar problem. Since last week the undo would not work anymore. I uninstalled/installed the add-on (4.1.1 on Firefox 58.0.2/Ubuntu Linux) several times. I disabled all other add-ons (except Tree Style App) without success. I installed other undo-close-tab-add-ons and they have the same problem, therefore it is probably a problem with my firefox or settings. It seems that the add-ons can not access the "recently closed tabs" list. Any tips? Thanks in advance!

**Comment by M-Reimer** [comment]
Please try a *new* profile.
I'm almost 100% sure that I can't fix these problems "on my side". It works for me (three installations) and for many other users.
Broken profiles have been a common Firefox problem for years.

**Comment by Filbuntu** [comment]
@M-Reimer Thank you for the tip. In the meantime it works again for me, probably a recent update of Firefox helped.

**Comment by M-Reimer** [comment]
As this one is most probably a Firefox problem that happens in rare cases, where I can't do much about, I'll close here.
