### ISSUE TITLE
No Longer working ?

### ISSUE THREAD

**Issue by ar-gh** [M-Reimer/undoclosetab#51]
Hello, Salut, ;)

It looks like that the plug-in doesn't work anymore.
Impossible to click on it, nothing happen...

If you could have a look at it !

**Comment by M-Reimer** [comment]
Definitively works :P
Please try uninstalling and reinstalling and report back.
This is more or less a known Firefox problem. Nothing that could be fixed by me.

**Comment by ar-gh** [comment]
Nope. Still the same problem.

**Comment by ar-gh** [comment]
https://www.numerama.com/tech/513627-firefox-mozilla-sort-des-add-ons-pour-resoudre-le-probleme-des-add-ons.html #Inception

**Comment by M-Reimer** [comment]
The certificate problem should be fixed already. You just have to get sure you have the latest Firefox version installed.

Create a new profile parallel to your existing one (google for "Profile manager") and install "Undo Close Tab" there. I'm almost 100% sure it will work there.

This is a problem that gets reported here from time to time. For some reason Addons get corrupted in profiles.

Would have to be fixed by Mozilla. Nothing I can do about this.

**Comment by M-Reimer** [comment]
Can you please test with a new profile?

**Comment by ar-gh** [comment]
It came back in order few days ago. :)

**Comment by M-Reimer** [comment]
So this can be closed, right? ;)
