### ISSUE TITLE
The Undo Tab Button no longer works

### ISSUE THREAD

**Issue by HANZ64** [M-Reimer/undoclosetab#57]
In fact it doesn't do anything at all.

I am using the latest version of Firefox to date (67.0.4) [21/06/2019]

I tried uninstalling/reinstalling but the button still doesn't do anything.

**Comment by M-Reimer** [comment]
Please try a new profile. Google for "profile manager" to find out how to create a second profile to your existing one.

**Comment by HANZ64** [comment]
Yes it works fine on a fresh install/new profile, but it doesn't work on my main profile. It was working fine for a while until one of your recent updates and/or Firefox updates.

I tried some older versions of this addon, but none of them seem to be working either.

**Comment by M-Reimer** [comment]
Create a backup of your profile files.
In your profile there are several files and directories which all start with "extension". Try to delete them.
Should result in your old profile with **all** addon settings reset and no addons installed at all.
Start over from there.
And tell me if this enables you to revive your profile.

This profile problem is a common Firefox thing.
Unfortunately I never had this problem in one of my profiles, so I, so far, wasn't able to really debug this. But even in this case, this has to be fixed by Mozilla. Not much I can do about this.

**Comment by M-Reimer** [comment]
This bug actually is just again the "profile corruption" problem.
https://github.com/M-Reimer/undoclosetab/issues/38

This is a Firefox bug that happens to some people from time to time. I'm sorry for that but I can't help in any way. This is your Firefox profile going corrupt in "some way". Mozilla would have to fix this. I never had this problem on any of my systems so I, so far, wasn't able to find out how to workaround this problem.

It should be possible to fix this by deleting "some" file in the profile. Actually it would be safe to delete nearly every file as long as you keep a backup of your profile. Restart the browser between every file delete to find out if this changed something.
If someone will ever come up with the right file, which needs deleting, I could add this to the README of this repository to help users with this problem.
Knowing the file which gets corrupt may also help Mozilla with fixing the bug on their side.
